### ISSUE TITLE
Street signs at the corner of Langhorne Road and Miller Park Square are swapped

### ISSUE THREAD

**Issue by teslahitchhiker42** [livable-lynchburg/lynchburg-road-issues#129] opened 2023-11-20 23:36 UTC
https://www.openstreetmap.org/#map=19/37.40388/-79.15923
![20231120_174356](https://github.com/partytax/lynchburg-road-issues/assets/66333762/945fd185-40cd-4cc0-b2d0-4683e241e133)

**Comment by partytax** [comment] 2024-01-09 15:53
@teslahitchhiker42 I'm beginning to think these are actually right. Langhorne Road sign is more or less aligned with Langhorne Road, and Miller Park Square sign is more or less aligned with Miller Park Square. Maybe the pole needs twisted a little counterclockwise when looking down from the sky?

**Comment by teslahitchhiker42** [comment] 2024-01-09 16:04
Maybe so? I'll try to take a closer look myself next day it's not raining.

**Comment by partytax** [comment] 2024-01-14 17:20
@teslahitchhiker42 confirmed in real life conversation that signs are actually correct. Closing.

**Comment by TimMagee** [comment] 2024-02-08 19:46
I suppose they technically aren't swapped because merely swapping them would make the situation worse.

However, the sign for Langhorne Rd is perpendicular to the stop sign and is not parallel to Langhorne Rd. This is still confusing and should still be fixed.

I understand why the sign for Miller Park Sq is not perpendicular to the stop sign. But the sign for Langhorne Rd should be parallel to Langhorne Rd and not perpendicular to the stop sign.

**Comment by partytax** [comment] 2024-02-09 02:40
Seems like all the square post sign holder brackets are fixed straight. There _are_ sign-to-sign brackets that are adjustable.

![Screenshot 2024-02-08 at 21-39-28 adjustable square post street sign bracket at DuckDuckGo](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/855b8d7c-4109-4b79-b11f-1b790fe1a890)

**Comment by partytax** [comment] 2024-02-09 02:42
So we'd have to do custom fabrication to turn the sign 15-20 degrees? Seems too involved for what we'd get out of it.

**Comment by partytax** [comment] 2024-03-05 17:09
@TimMagee @teslahitchhiker42 What are you thinking on this one?

**Comment by partytax** [comment] 2024-06-19 13:35
@teslahitchhiker42 @TimMagee Thoughts?

**Comment by partytax** [comment] 2024-09-23 21:33
Intractable and annoying...closing

**Closed by partytax** 2024-09-23 21:33 UTC
Labels: bug, AUTHORITY:LYH-PW
